### ISSUE TITLE
The setuptools-scm setup requirement is too old

### ISSUE THREAD

**Issue by zvezdan** [Tblue/pytest-datadir-ng#5]
This _pytest-datadir-ng_ package specifies `setup_requires=["setuptools_scm ~= 1.10"]`, which restricts _setuptools-scm_ to `>= 1.10, == 1.*` and that is **incompatible** with the main feature that _setuptools-scm_ is used for here: **auto-versioning**. Line [7 in setup.py](https://github.com/Tblue/pytest-datadir-ng/blob/1.1.1/setup.py#L7) for the latest release 1.1.1 sets `use_scm_version=True`. According to [setuptools-scm documentation](https://github.com/pypa/setuptools_scm/), the minimum version for using this feature is _setuptools-scm-3.4_ + setuptools-42.

A typical, large, build environment must provide the correct version of _setuptools_ and _setuptools-scm_ to get the auto-versioning feature of _setuptools-scm_ working correctly for all packages with or without [PEP 518](https://www.python.org/dev/peps/pep-0518/) support. Otherwise, some of them may build with version 0.0.0. In such environment, the _pytest-datadir-ng_ package can cause failures that look like this (line breaks added for easier reading):
```
Processing .../pytest-datadir-ng-1.1.0.tar.gz
...
.../site-packages/setuptools/dist.py:724: 
UserWarning: Module setuptools_scm was already imported from .../site-packages/setuptools_scm/__init__.py,
but .../pip-req-build-6y9wra68/.eggs/setuptools_scm-1.15.5-py3.7.egg is being added to sys.path
      pkg_resources.working_set.add(dist, replace=True)
    Traceback (most recent call last):
      File ".../site-packages/pkg_resources/__init__.py", line 2451, in resolve
        return functools.reduce(getattr, self.attrs, module)
    AttributeError: module 'setuptools_scm.hg' has no attribute 'FILES_COMMAND'
```
because the version `>= 1.10, == 1.*` is _too old_.
The selected compatible version (1.15.5 in this case) does not allow the use of version 3.4 (or better) that is actually needed by much newer setuptools-42 (or better). The pkg_resources that raises this error is a part of setuptools.

Can we change this requirement to `setup_requires=["setuptools_scm ~= 3.4"]` instead?
Perhaps even better: `setup_requires=["setuptools_scm >= 3.4"]`?
If necessary add a restriction such as `, <6` or any other upper limit that's considered correct for the particular release of _pytest-datadir-ng_.

**Comment by zvezdan** [comment]
Looking into the reasons for this pin, it seems that the release 1.1.0 of _pytest-datadir-ng_, from 2016, pinned the setup requirement for setuptools-scm to version compatible with 1.10. That may have been a good version of setuptools-scm back in 2016, but it is definitely obsolete now. Then, the most recent release of _pytest-datadir-ng_ 1.1.1 **inherited** this obsolete setup requirement instead of upgrading it to 3.4 or higher. It seems that the main goal of that release was to add just the LICENSE file, so nothing else was changed in 2019, although this pin in setup requirements should have been re-examined.

Applying a simple hotfix like this to the sdist of 1.1.1 solves the problem:
```diff
diff -ur pytest-datadir-ng-1.1.1/PKG-INFO pytest-datadir-ng-1.1.1.1/PKG-INFO
--- pytest-datadir-ng-1.1.1/PKG-INFO    2019-12-24 18:23:18.950229600 -0800
+++ pytest-datadir-ng-1.1.1.1/PKG-INFO  2021-02-09 19:03:24.442302780 -0800
@@ -1,6 +1,6 @@
 Metadata-Version: 1.1
 Name: pytest-datadir-ng
-Version: 1.1.1
+Version: 1.1.1.1
 Summary: Fixtures for pytest allowing test functions/methods to easily retrieve test resources from the local filesystem.
 Home-page: https://github.com/Tblue/pytest-datadir-ng
 Author: Tilman Blumenbach
diff -ur pytest-datadir-ng-1.1.1/README.rst pytest-datadir-ng-1.1.1.1/README.rst
--- pytest-datadir-ng-1.1.1/README.rst  2019-12-24 18:17:17.000000000 -0800
+++ pytest-datadir-ng-1.1.1.1/README.rst        2021-02-09 19:01:08.571943552 -0800
@@ -150,6 +150,12 @@
 Version history
 ---------------
+Version 1.1.1.1
++++++++++++++++
+
+- Upgrade obsolete ``setup_requires`` dependency on `setuptools-scm-1.x`
+  to 3.4 or higher.
+
 Version 1.1.1
 +++++++++++++
diff -ur pytest-datadir-ng-1.1.1/pytest_datadir_ng.egg-info/PKG-INFO pytest-datadir-ng-1.1.1.1/pytest_datadir_ng.egg-info/PKG-INFO
--- pytest-datadir-ng-1.1.1/pytest_datadir_ng.egg-info/PKG-INFO 2019-12-24 18:23:18.000000000 -0800
+++ pytest-datadir-ng-1.1.1.1/pytest_datadir_ng.egg-info/PKG-INFO       2021-02-09 19:01:25.097865614 -0800
@@ -1,6 +1,6 @@
 Metadata-Version: 1.1
 Name: pytest-datadir-ng
-Version: 1.1.1
+Version: 1.1.1.1
 Summary: Fixtures for pytest allowing test functions/methods to easily retrieve test resources from the local filesystem.
 Home-page: https://github.com/Tblue/pytest-datadir-ng
 Author: Tilman Blumenbach
diff -ur pytest-datadir-ng-1.1.1/setup.py pytest-datadir-ng-1.1.1.1/setup.py
--- pytest-datadir-ng-1.1.1/setup.py    2019-12-24 18:13:11.000000000 -0800
+++ pytest-datadir-ng-1.1.1.1/setup.py  2021-02-09 19:02:03.128686260 -0800
@@ -26,7 +26,7 @@
     url="https://github.com/Tblue/pytest-datadir-ng",
     py_modules=["pytest_datadir_ng"],
     install_requires=["pytest"],
-    setup_requires=["setuptools_scm ~= 1.10"],
+    setup_requires=["setuptools_scm >= 3.4"],
     classifiers=[
         "Development Status :: 5 - Production/Stable",
         "Intended Audience :: Developers",
```
The new sdist for this 1.1.1.1 hotfix can be rebuilt using `python setup.py sdist`.

Of course, applying this one line change from _setup.py_ file only to the HEAD of development here and releasing it as _pytest-datadir-ng-1.2.0_ (or 1.1.2 if you feel it doesn't warrant minor version increase) should help anyone who depends on this package in the future.

**Comment by Tblue** [comment]
Apologies for the late reply.

So the core issue here seems to be that the `setuptools_scm` version is ancient. Got it, I will upgrade it.

**Comment by Tblue** [comment]
Welp, I think I was too hasty to simply use `setuptools_scm~=6.0` since that requires Python 3.6 or later, but I'd say we should still support Python 2.7.

**Comment by Tblue** [comment]
Then again, might be a good opportunity to drop Python 2 support.
